// .devdev/carr/ui/src/routes/posts/[id]/EditLink.svelte
<script lang="ts">
	import { ArrowBigRightDash } from 'lucide-svelte'

	let { id }: { id: number } = $props()
</script>

<a href={`/posts/${id}/edit`}>
	<ArrowBigRightDash class="inline w-4" />
	<span>Edit</span>
</a>

<style lang="postcss">
	@reference "#app.css";

	a {
		@apply font-zenkaku block w-fit mx-3 my-3;
	}
	span {
		@apply inline-block border-b-2 border-dotted;
		@apply hover:border-dashed;
	}
</style>

// aws-transform-custom-try/oldapp/src/app/posts/[id]/EditLink.tsx
'use client'

import { ArrowBigRightDash } from 'lucide-react'
import Link from 'next/link'

interface EditLinkProps {
  id: number
}

export default function EditLink({ id }: EditLinkProps) {
  return (
    <Link href={`/posts/${id}/edit`} className="font-zenkaku block w-fit mx-3 my-3">
      <ArrowBigRightDash className="inline w-4" />
      <span className="inline-block border-b-2 border-dotted hover:border-dashed">Edit</span>
    </Link>
  )
}
