// google-cloud-recaptcha-try/sampleapp/src/routes/posts/[id]/+page.svelte
<script lang="ts">
	import PageTitle from '$lib/components/PageTitle.svelte'
	import EditLink from './EditLink.svelte'
	import { getPost } from '$lib/api/posts'

	let { data } = $props()
	let post = $derived(getPost(data.id))
</script>

<PageTitle title="Detail" />

{#if post.data !== undefined}
	<div class="text-lg px-3 bg-grayer py-5">
		{post.data.title}
	</div>
	<EditLink id={data.id} />
{/if}

// aws-transform-custom-try/oldapp/src/app/posts/[id]/page.tsx
'use client'

import { useParams } from 'next/navigation'
import { notFound } from 'next/navigation'
import PageTitle from '@/lib/components/PageTitle'
import { useGetPost } from '@/lib/api/posts'
import EditLink from './EditLink'

export default function PostDetailPage() {
  const params = useParams()
  const id = Number(params.id)

  if (Number.isNaN(id)) {
    notFound()
  }

  const post = useGetPost(id)

  return (
    <>
      <PageTitle title="Detail" />

      {post.data !== undefined && (
        <>
          <div className="text-lg px-3 bg-grayer py-5">
            {post.data.title}
          </div>
          <EditLink id={id} />
        </>
      )}
    </>
  )
}
