// aws-transform-custom-try/oldapp/src/app/components/Header.tsx
import { Cloud } from 'lucide-react'
import Link from 'next/link'

export default function Header() {
  return (
    <header className="container mx-auto pt-2 pb-4 mb-4">
      <Link href="/" className="inline-block">
        <h1 className="font-zenkaku text-2xl font-bold px-2">
          my-svelte-template <Cloud className="inline" />
        </h1>
      </Link>
    </header>
  )
}

// lolipop-deploynow-try/src/routes/Header.svelte
<script lang="ts">
	import { Cloudy } from 'lucide-svelte'
</script>

<header>
	<a href="/" class="inline-block">
		<h1>
			my-svelte-template <Cloudy class="inline" />
		</h1>
	</a>
</header>

<style lang="postcss">
	@reference "#app.css";

	header {
		@apply container mx-auto pt-2 pb-4 mb-4;
	}
	h1 {
		@apply font-zenkaku text-2xl font-bold px-2;
	}
</style>
